//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagScanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagScanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Down_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Down_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Up_16xLG {
            get {
                object obj = ResourceManager.GetObject("arrow_Up_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse {
            get {
                object obj = ResourceManager.GetObject("Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand_32 {
            get {
                object obj = ResourceManager.GetObject("Expand_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_Open_16xLG {
            get {
                object obj = ResourceManager.GetObject("folder_Open_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_6296 {
            get {
                object obj = ResourceManager.GetObject("Open_6296", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_16xLG {
            get {
                object obj = ResourceManager.GetObject("refresh_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recent Folder.
        /// </summary>
        internal static string S_AddRecentFolder {
            get {
                return ResourceManager.GetString("S_AddRecentFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string S_Cancel {
            get {
                return ResourceManager.GetString("S_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Continue to synchronize and save?.
        /// </summary>
        internal static string S_ConfirmSync {
            get {
                return ResourceManager.GetString("S_ConfirmSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronise library file.
        /// </summary>
        internal static string S_ConfirmSyncCaption {
            get {
                return ResourceManager.GetString("S_ConfirmSyncCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        internal static string S_CustomDateTimeFormat {
            get {
                return ResourceManager.GetString("S_CustomDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error streaming track.
        /// </summary>
        internal static string S_ErrorStreamingTrack {
            get {
                return ResourceManager.GetString("S_ErrorStreamingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of this file have changed. Do you want to save the changes?.
        /// </summary>
        internal static string S_FileContentsHaveChanged {
            get {
                return ResourceManager.GetString("S_FileContentsHaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File modified.
        /// </summary>
        internal static string S_FileModified {
            get {
                return ResourceManager.GetString("S_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; no longer exists. Remove from menu?.
        /// </summary>
        internal static string S_FileNoLongerExists {
            get {
                return ResourceManager.GetString("S_FileNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; no longer exists. Remove from menu?.
        /// </summary>
        internal static string S_FolderNoLongerExists {
            get {
                return ResourceManager.GetString("S_FolderNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string S_Replace {
            get {
                return ResourceManager.GetString("S_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} replacement(s) made..
        /// </summary>
        internal static string S_ReplacementsMade {
            get {
                return ResourceManager.GetString("S_ReplacementsMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace preview - {0} matches found.
        /// </summary>
        internal static string S_ReplacePreview {
            get {
                return ResourceManager.GetString("S_ReplacePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopen file.
        /// </summary>
        internal static string S_RepoenFile {
            get {
                return ResourceManager.GetString("S_RepoenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        internal static string S_SaveFile {
            get {
                return ResourceManager.GetString("S_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to open.
        /// </summary>
        internal static string S_SelectFileToOpen {
            get {
                return ResourceManager.GetString("S_SelectFileToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the media file(s) to add.
        /// </summary>
        internal static string S_SelectTheMediaFilesToAdd {
            get {
                return ResourceManager.GetString("S_SelectTheMediaFilesToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the media folder to add.
        /// </summary>
        internal static string S_SelectTheMediaFolderToAdd {
            get {
                return ResourceManager.GetString("S_SelectTheMediaFolderToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- {0:n0} new track(s) will be added to the library file.
        ///.
        /// </summary>
        internal static string S_TracksAdded {
            get {
                return ResourceManager.GetString("S_TracksAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may synchronise the library file with the ID3 track data in your media prior to saving. If you choose to do this, the following {0:n0} operation(s) will be performed:
        ///
        ///.
        /// </summary>
        internal static string S_TracksChanged {
            get {
                return ResourceManager.GetString("S_TracksChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The previously loaded ID3 tag data of {0:n0} missing track(s) will be removed from the library file.
        ///.
        /// </summary>
        internal static string S_TracksDeleted {
            get {
                return ResourceManager.GetString("S_TracksDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The embedded ID3 tag data of {0:n0} track(s) will be overwritten to match the current contents of the library file.
        ///.
        /// </summary>
        internal static string S_TracksPending {
            get {
                return ResourceManager.GetString("S_TracksPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- The contents of the library file will be updated to match the currently embedded ID3 tag data of {0:n0} track(s).
        ///.
        /// </summary>
        internal static string S_TracksUpdated {
            get {
                return ResourceManager.GetString("S_TracksUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///{1}
        ///Version {2}.
        /// </summary>
        internal static string S_Version {
            get {
                return ResourceManager.GetString("S_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Views_7953_32 {
            get {
                object obj = ResourceManager.GetObject("Views_7953_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
